
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 22 03:41:28 CEST 2015
//----------------------------------------------------

package net.etfbl.kki;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 44;
  public static final int DECREAMENT = 19;
  public static final int LBRACKET = 39;
  public static final int GREATER_OR_EQUAL = 23;
  public static final int CONST = 15;
  public static final int CHAR_LITERAL = 43;
  public static final int ASSIGNMENT = 28;
  public static final int DEVIDE = 30;
  public static final int NUMBER_LITERAL = 41;
  public static final int NOT_EQUAL = 21;
  public static final int LPAREN = 34;
  public static final int GREATER = 22;
  public static final int SEMI = 32;
  public static final int INVALID = 45;
  public static final int LESS = 24;
  public static final int MINUS = 27;
  public static final int RPAREN = 35;
  public static final int LESS_OR_EQUAL = 25;
  public static final int COMMA = 33;
  public static final int CLASS = 6;
  public static final int PLUS = 26;
  public static final int IF = 9;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 38;
  public static final int EQUAL = 20;
  public static final int LOGICAL_OR = 16;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 31;
  public static final int IDENT = 46;
  public static final int BREAK = 13;
  public static final int VOID = 5;
  public static final int TIMES = 29;
  public static final int LBRACE = 36;
  public static final int ELSE = 10;
  public static final int READ = 12;
  public static final int WHILE = 11;
  public static final int LOGICAL_AND = 17;
  public static final int RBRACE = 37;
  public static final int EXTENDS = 7;
  public static final int INCREAMENT = 18;
  public static final int BOOL_LITERAL = 42;
  public static final int PRINT = 3;
  public static final int DO = 14;
}

