
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 23 02:54:32 CEST 2015
//----------------------------------------------------

package net.etfbl.kki;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 45;
  public static final int DECREAMENT = 20;
  public static final int LBRACKET = 40;
  public static final int GREATER_OR_EQUAL = 24;
  public static final int CONST = 16;
  public static final int CHAR_LITERAL = 44;
  public static final int ASSIGNMENT = 29;
  public static final int DEVIDE = 31;
  public static final int NUMBER_LITERAL = 42;
  public static final int NOT_EQUAL = 22;
  public static final int LPAREN = 35;
  public static final int GREATER = 23;
  public static final int SEMI = 33;
  public static final int INVALID = 46;
  public static final int LESS = 25;
  public static final int MINUS = 28;
  public static final int RPAREN = 36;
  public static final int LESS_OR_EQUAL = 26;
  public static final int COMMA = 34;
  public static final int CLASS = 6;
  public static final int PLUS = 27;
  public static final int IF = 9;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 39;
  public static final int EQUAL = 21;
  public static final int LOGICAL_OR = 17;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 32;
  public static final int IDENT = 47;
  public static final int BREAK = 14;
  public static final int VOID = 5;
  public static final int TIMES = 30;
  public static final int LBRACE = 37;
  public static final int ELSE = 10;
  public static final int READ = 12;
  public static final int WHILE = 11;
  public static final int LOGICAL_AND = 18;
  public static final int RBRACE = 38;
  public static final int EXTENDS = 7;
  public static final int LEN = 13;
  public static final int INCREAMENT = 19;
  public static final int BOOL_LITERAL = 43;
  public static final int PRINT = 3;
  public static final int DO = 15;
}

